spring:
  datasource:
    url: jdbc:mysql://localhost:3306/9173?allowMultiQueries=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 0503
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.cwgl.entity

logging:
  level:
    root: info
    org:
      springframework:
        web: info
    com.example.cwgl.dao: debug
server:
  port: 8089
